###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
image:
  repository: skydive/skydive
  tag: 1

## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  storage:
    size: 2Gi
    class: 
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

service:
  name: skydive
  type: NodePort
  port: 8082
  