apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skydive-analyzer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skydive
        tier: analyzer
    spec:
      containers:
      - name: skydive-analyzer
        image: skydive/skydive
        args:
        - analyzer
        - --listen=0.0.0.0:8082
        ports:
        - containerPort: 8082
        - containerPort: 8082
          protocol: UDP
        - containerPort: 12379
        env:
        - name: SKYDIVE_ANALYZER_STORAGE_BACKEND
          value: elasticsearch
        - name: SKYDIVE_GRAPH_BACKEND
          value: elasticsearch
        - name: SKYDIVE_ETCD_LISTEN
          value: 0.0.0.0:12379
      - name: skydive-elasticsearch
        image: elasticsearch:2
        ports:
        - containerPort: 9200
