apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: api
  - port: {{ .Values.service.port }}
    name: protobuf
    protocol: UDP
  - port: 12379
    name: etcd
  - port: 9200
    name: es
  selector:
    app: {{ template "name" . }}
    tier: analyzer